// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutricional.Data;

namespace Nutricional.Migrations
{
    [DbContext(typeof(AlimentoContext))]
    partial class AlimentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Nutricional.Models.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Calorias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Carboidrato")
                        .HasColumnType("double");

                    b.Property<double>("Cinzas")
                        .HasColumnType("double");

                    b.Property<string>("Cobre")
                        .HasColumnType("text");

                    b.Property<string>("Colesterol")
                        .HasColumnType("text");

                    b.Property<double>("Cálcio")
                        .HasColumnType("double");

                    b.Property<string>("DescricaoNutricional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Energia")
                        .HasColumnType("double");

                    b.Property<double>("Ferro")
                        .HasColumnType("double");

                    b.Property<double>("FibraAlimentar")
                        .HasColumnType("double");

                    b.Property<double>("Fósforo")
                        .HasColumnType("double");

                    b.Property<string>("GrupoAlimentar")
                        .HasColumnType("text");

                    b.Property<double>("Lipídeos")
                        .HasColumnType("double");

                    b.Property<double>("Magnésio")
                        .HasColumnType("double");

                    b.Property<string>("Manganês")
                        .HasColumnType("text");

                    b.Property<string>("Niacina")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Piridoxina")
                        .HasColumnType("text");

                    b.Property<double>("Potássio")
                        .HasColumnType("double");

                    b.Property<double>("Proteína")
                        .HasColumnType("double");

                    b.Property<string>("RAE")
                        .HasColumnType("text");

                    b.Property<string>("RE")
                        .HasColumnType("text");

                    b.Property<string>("Retinol")
                        .HasColumnType("text");

                    b.Property<string>("Riboflavina")
                        .HasColumnType("text");

                    b.Property<double>("Sódio")
                        .HasColumnType("double");

                    b.Property<string>("Tiamina")
                        .HasColumnType("text");

                    b.Property<double>("Umidade")
                        .HasColumnType("double");

                    b.Property<string>("VitaminaC")
                        .HasColumnType("text");

                    b.Property<double>("Zinco")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Alimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
